nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:4200']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        expose_headers: ['Authorization']
        max_age: 3600
    paths:
        '^/api/': # Appliquer la règle aux routes API
            allow_origin: ['http://localhost:4200']
